---
abstract: 贴子下载器
author:
  - 'abbypan <abbypan@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.008, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tiezi-Robot
requires:
  Encode::Locale: 0
  JSON: 0
  Novel::Robot::Browser: 0
  Term::Menus: 0
  Tiezi::Robot::Packer: 0
  Tiezi::Robot::Parser: 0
version: 0.15
