---
abstract: 贴子下载器
author:
  - 'abbypan <abbypan@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tiezi-Robot
requires:
  Encode::Locale: 1.03
  JSON: 2.53
  Moo: 1.000007
  Novel::Robot::Browser: 0.06
  Term::Menus: 2.21
  Tiezi::Robot::Packer: 0.01
  Tiezi::Robot::Parser: 0.05
version: 0.09
