=pod

=encoding utf8

=head1 USAGE

    #取出指定帖子，只看楼主，且跟帖内容不能少于100字 

    tiezi_to_html.pl -u "http://bbs.jjwxc.net/showmsg.php?board=153&id=57" -U 1 -C 100

=head1 OPTIONS

-s : 站点类型

-u : 帖子url

-f : 输出html文件名(默认是 作者-帖子标题.html)


-P : 取 top n 页

-F : 取 top n 楼

-W : 跟贴至少要 n 个字

-U : 只看楼主(默认是取出所有楼层，不只楼主)

-T : 生成的贴子不加楼层目录(默认是加楼层目录)

=cut
